create table roles (
    id int8 generated by default as identity,
    created_at timestamp not null,
    deleted_at timestamp,
    update_at timestamp,
    role varchar(255),
    primary key (id)
    );

create table departments (
    id int8 generated by default as identity,
    created_at timestamp not null,
    deleted_at timestamp,
    update_at timestamp,
    description TEXT,
    short_description varchar(255),
    image varchar(255),
    name varchar(255),
    primary key (id)
    );

create table comments (
    id int8 generated by default as identity,
    created_at timestamp not null,
    deleted_at timestamp,
    update_at timestamp,
    comment TEXT,
    blogs_id int8,
    users_id int8,
    primary key (id)
    );

create table users (
    id int8 generated by default as identity,
    created_at timestamp not null,
    deleted_at timestamp,
    update_at timestamp,
    avatar varchar(255),
    email varchar(255),
    fullname varchar(255),
    password varchar(255),
    primary key (id)
    );

create table blogs (
    id int8 generated by default as identity,
    created_at timestamp not null,
    deleted_at timestamp,
    update_at timestamp,
    description TEXT,
    image varchar(255),
    short_title varchar(255),
    title varchar(512),
    users_id int8,
    primary key (id)
    );

create table doctor (id int8 generated by default as identity,
    created_at timestamp not null,
    deleted_at timestamp,
    update_at timestamp,
    image varchar(255),
    name varchar(255),
    surname varchar(255),
    speciality_id int8,
    primary key (id)
    );

create table speciality (
    id int8 generated by default as identity,
    created_at timestamp not null,
    deleted_at timestamp,
    update_at timestamp,
    spec_name varchar(255),
    short_code varchar(255),
    primary key (id)
                        );



create table users_roles (
    users_id int8 not null,
    roles_id int8 not null
    );

alter table if exists blogs
    add constraint FKfic1v0xnjyrmw6ieggp0vcs48
    foreign key (users_id) references users;

alter table if exists comments
    add constraint FKioiayeyrmynqfmglrg80kts4y
    foreign key (blogs_id) references blogs;

alter table if exists comments
    add constraint FKt55y2infwbbw3o942o2mhm0v4
        foreign key (users_id) references users;

alter table if exists doctor
    add constraint FKdht1k3ou6ody790hip20bl9dx
        foreign key (speciality_id) references speciality;

alter table if exists users_roles
    add constraint FKa62j07k5mhgifpp955h37ponj
        foreign key (roles_id) references roles;

alter table if exists users_roles
    add constraint FKml90kef4w2jy7oxyqv742tsfc
        foreign key (users_id) references users;
